osx_image: xcode61
language: objective-c

env:
  global:
    secure: "KlLWvDgrMG0FseF26oNMChQ18NJmz4TLC4+V5y6i4XBD3HvSx2+LC+Zq1BL7t+7iK8ZJ+n5VmC0kWBfn4TfM95wAHhD49lJGwu5JkGSmqDMioEQQ6oX4YmlWMbUULiutvF5+ryxm45gQP3mZq7X/SWr34lQRVnexoX3WpekXL0I="

cache:
  - bundler
  - cocoapods

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - echo $GITHUB_API_KEY
  - echo "machine github.com login $GITHUB_API_KEY" > ~/.netrc
  - head ~/.netrc
  - chmod 600 ~/.netrc
  - pod repo add artsy https://github.com/artsy/Specs.git

install:
  - bundle install
  - make pods

before_script:
  - make ci

script:
  - make test
  - make lint

notifications:
  slack:
    secure: "fXmNnx6XW5OvT/j2jSSHYd3mHwbL+GzUSUSWmZVT0Vx/Ga5jXINTOYRY/9PYgJMqdL8a/L0Mf/18ZZ+tliPlWQ/DnfTz1a3Q/Pf94hfYSGhSGlQC/eXYcpOm/dNOKYQ3sr4tqXtTPylPUDXHeiM2D59ggdlUvVwcALGgHizajPQ="
