# Because we don't run all tests on every PR, adding the label "build-me" to a PR will trigger all tests to run on CircleCI.
name: Run all js tests on "build-me" label
on:
  pull_request:
    types:
      - labeled

jobs:
  trigger:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    steps:
      - name: Trigger all js tests
        run: |
          curl \
            -X POST \
            --header "Content-Type: application/json" \
            -d "{\"branch\": \"$GITHUB_HEAD_REF\"}" \
            https://circleci.com/api/v1.1/project/github/artsy/eigen/build?circle-token=${{ secrets.CircleToken }}
